config/routes.rb
Rails.application.routes.draw do
  root to: 'static#index'
  get '/signin', to: 'sessions#new', as: 'signin'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'

  get 'auth/google_oauth2/callback', to: 'sessions#google'
  resources :users, except: [:new]

  resources :books do
    resources :reviews, shallow: true
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :author
  has_many :reviews
  validates_presence_of :title, :author
  validates_with InnocenceValidator

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
  scope :alphabetical_order, -> { order(:content)}
  scope :in_last_year, -> {where('created_at >= ?', 1.year.ago)}
  scope :last_3, -> { order(created_at: :desc).limit(3)}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  has_many :reviews
  has_secure_password
  validates :password, length: { in: 6..72 }
  validates_presence_of :email, :username
  validates_uniqueness_of :email, :username, { case_sensitive: false }

  def reviews_in_last_year
    reviews.in_last_year
  end

  def self.find_or_create_with_oauth(auth)
    u = User.find_by_uid(auth["uid"]) || User.find_or_create_by_email(auth)
    u.email = auth["info"]["email"]
    u.uid = auth["uid"]
    binding.pry
    u.save
    u
  end

  def self.find_or_create_by_email(auth)
    User.find_or_create_by(email: auth["info"]["email"]) do |u|
      u.uid = auth["uid"]
      u.password = SecureRandom.hex(20)
      u.username = auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in
  before_action :redirect_if_logged_out


  private
  def current_user
    @user ||= User.find_by(id: session[:user_id])
  end

  def logged_in
    !!current_user
  end

  def redirect_if_logged_out
    unless logged_in
      redirect_to root_path, notice: "You must be logged in to do that"
    end
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def show
    @author = Author.find(params[:id])
  end

  def new

    @author = Author.new

  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to @author
    else
      render :new

    end
  end

  private

  def author_params
    params.require(:author).permit(:name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  skip_before_action :redirect_if_logged_out, only: [:index]
  # GET /books
  # GET /books.json
  def index
    binding.pry
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.build(book_params)
      if @book.save
        redirect_to @book, notice: 'Book was successfully created.'
      else
        render :new
      end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    redirect_if_wrong_user
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end
    def redirect_if_wrong_user

    end
    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :description)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @book = Book.find(params[:book_id])

    @reviews = @book.reviews
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @book = Book.find(params[:book_id])
    @review = Review.new
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to book_reviews_path(@review.book)
    else
      render :edit
    end
  end

  def create
    @review = current_user.reviews.build(**review_params, book_id: params[:book_id])
    if @review.save
      redirect_to redirect_to book_reviews_path(@review.book), notice: "Review successfully created."
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :redirect_if_logged_out

  def create
    @user = User.find_by(username: params[:username])
    if @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to books_path
    else
      @error = "Incorrect username and/or password"
      render :new
    end
  end

  def google
    u = User.find_or_create_with_oauth(auth)
    session[:user_id] = u.id

    redirect_to '/books'
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  skip_before_action :redirect_if_logged_out
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :redirect_if_logged_out, only: [:new, :create]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def update

  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to '/'
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def display_title(book)
    book.title.downcase
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/new.html.erb
<%= form_for @author do |f|%>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>

app/views/authors/show.html.erb
<h1><%= @author.name %></h1>

<% if @author.books.empty? %>
<p>No books for this author yet.</p>
<% else %>
<% @author.books.each do |b|%>
<%= render "books/book", book: b %>
<% end %>
<% end %>

<%= link_to  "Add a book to this author", new_author_book_path(@author) %>

app/views/books/_author_book_form.html.erb
<%= form_for([author, book], local: true) do |form| %>
<%= render 'shared/errors', instance: book %>

<div class="field">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="field">
  <%= form.label :description %>
  <%= form.text_field :description %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/books/_book.html.erb
<tr>
  <td><%= display_title(book) %></td>
  <td><%= book.author.name %></td>
  <td><%= book.description %></td>
  <td><%= link_to 'Show', book %></td>
  <td><%= link_to 'Edit', edit_book_path(book) %></td>
  <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/books/_form.html.erb
<%= form_for(@book, local: true) do |form| %>
<%= render 'shared/errors', instance: @book %>

<div class="field">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="field">
  <%= form.select :author_id,
    options_from_collection_for_select(@authors, :id, :name), :prompt => "Select Author"
    %>
</div>

<div class="field">
  <%= form.label :description %>
  <%= form.text_field :description %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
    <%= render 'book', book: book%>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book<%= @author ? " by #{@author.name}" : "" %></h1>
<% if !@author %>
<%= render 'form' %>
<% else %>
<%= render 'author_book_form', author: @author, book: @book %>
<% end %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<h1>This book belongs to <%= @book.user.username %> </h1>
<%= render 'book', book: @book %>
<%= link_to 'Review this book', new_book_review_path(@book) %>
<h2>Last 3 Reviews</h2>
<% @book.reviews.last_3.each do |r| %>
<p>Rating: <%= r.rating %></p>
<p><%= r.content%></p>
<p>- <%= r.user.username %></p>
<% end %>
<%= link_to 'See All Reviews for this Book', book_reviews_path(@book) %>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
  <html>

  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in %>
    <%= link_to 'Log out', '/signout', method: :delete %>
    <% end %>
    <p id="notice"><%= notice %></p>
    <%= yield %>
  </body>

  </html>

app/views/reviews/edit.html.erb
<%= form_for @review do |f| %>
<% if @review.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@review.errors.count, "error") %> prohibited this @review from being saved:</h2>

  <ul>
    <% @review.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :rating %>
  <%= f.select(:rating, [1,2,3,4,5], :prompt => 'Rating (1-5)') %>
</div>

<div class="field">
  <%= f.label :content %>
  <%= f.text_area :content %>
</div>

<div class="actions">
  <%= f.submit %>
</div>

<% end %>

app/views/reviews/index.html.erb
<h2>Reviews</h2>
<% @reviews.each do |r| %>
<p>Rating: <%= r.rating %></p>
<p><%= r.content%></p>
<p>- <%= r.user.username %></p>
<% end %>

app/views/reviews/new.html.erb
<%= form_for @review do |f| %>
<% if @review.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@review.errors.count, "error") %> prohibited this @review from being saved:</h2>

  <ul>
    <% @review.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :book_id %>
  <%= f.select(:book_id, @books.map{|b| [b.title, b.id]},
  prompt: 'Select a book',
  selected: @book_id) %>
</div>

<div class="field">
  <%= f.label :rating %>
  <%= f.select(:rating, [1,2,3,4,5], :prompt => 'Rating (1-5)') %>
</div>

<div class="field">
  <%= f.label :content %>
  <%= f.text_area :content %>
</div>

<div class="actions">
  <%= f.submit %>
</div>

<% end %>

app/views/reviews/show.html.erb
<p>Rating: <%= @review.rating %></p>
<p><%= @review.content%></p>
<p>- <%= @review.user.username %></p>

app/views/shared/_errors.html.erb
<% if instance.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(instance.errors.count, "error") %> prohibited this <%= instance.class.name.downcase %> from being saved:</h2>

  <ul>
    <% instance.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_review_list.erb
<h2>Reviews</h2>
<% parent.reviews.in_last_year.each do |r| %>
<p>Rating: <%= r.rating %></p>
<p><%= r.content%></p>
<p>- <%= r.user.username %></p>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
<%= render 'shared/errors', instance: @user %>

<div class="field">
  <%= form.label :username %>
  <%= form.text_field :username %>
</div>

<div class="field">
  <%= form.label :email %>
  <%= form.text_field :email %>
</div>

<div class="field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'form' %>
OR
<%= link_to "Sign up with Google", '/auth/google_oauth2', method: :post %>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%=@user.username %>
<%=  link_to 'delete', user_path, method:'delete'%>
<p>This user has written <%= @user.reviews_in_last_year.count %> reviews in the last year.</p>
<%= render 'shared/review_list', parent: @user %>